apt-get install liblua5.1-filesystem0 
apt-get install libgstreamer0.10-dev 
apt-get install libgstreamer-plugins-base0.10-dev 
apt-get install libavcodec-dev 
apt-get install libavformat-dev 
apt-get install libavutil-dev 
apt-get install libswscale-dev 
apt-get install freeglut3-dev 
apt-get install libasound2-dev 
apt-get install libxmu-dev 
apt-get install libxxf86vm-dev 
apt-get install g++ 
apt-get install libgl1-mesa-dev 
apt-get install libglu1-mesa-dev 
apt-get install libraw1394-dev 
apt-get install liblua5.1-0-dev 
apt-get install libluajit-5.1-dev
apt-get install lua5.1 
apt-get install luarocks 
apt-get install libfreeimage-dev 
apt-get install libgtk2.0-dev 
apt-get install libapr1-dev 
apt-get install libmysqlclient15-dev 
apt-get install libqt4-dev 
apt-get install gstreamer0.10-ffmpeg 
apt-get install libjack-dev 
apt-get install libudev-dev 
apt-get install libmjpegtools-dev 
apt-get install libdts-dev 
apt-get install libhal-dev 
apt-get install gstreamer0.10-plugins-bad 
apt-get install libsndfile1-dev 
apt-get install portaudio19-dev 
apt-get install libcsound64-dev 
apt-get install libcsnd-dev
apt-get install libc6-dev-i386

