#ifndef VIDEO_VIDEO_COMMON_H
#define VIDEO_VIDEO_COMMON_H 1

namespace video {

enum VideoError{
	VIDEO_ERROR_NONE = 0,
	VIDEO_ERROR_GENERIC,
	VIDEO_ERROR_OPENGL,
	VIDEO_ERROR_MEMORY,
	VIDEO_ERROR_INVALID_ENUM,
	VIDEO_ERROR_INVALID_OPERATION
};

enum PixelFormat{
	PIX_FMT_RGB,
	PIX_FMT_RGBA
};

} // video::

#endif // VIDEO_VIDEO_COMMON_H
