#!/bin/sh

O_IFS=$IFS
IFS=""

notdone=`grep -e '^< .*' OBJECTS.txt`
done=`grep -e '^> .*' OBJECTS.txt`

notdone_count=`echo $notdone | wc -l | cut -b7-`
done_count=`echo $done | wc -l | cut -b7-`
total_count=`expr $notdone_count + $done_count`

echo $done_count out of $total_count objects completed

echo Still to be done:
echo $notdone

IFS=$O_IFS
