const char * av_ffi_header = ""
"local header = [[ \n"
"// generated from av.h on Sun Mar  3 22:41:50 2013 \n"
"void av_sleep(double seconds); \n"
"double av_time(); \n"
"enum { \n"
" AV_KEY_ENTER =3, \n"
" AV_KEY_BACKSPACE =8, \n"
" AV_KEY_TAB =9, \n"
" AV_KEY_RETURN =13, \n"
" AV_KEY_ESCAPE =27, \n"
" AV_KEY_DELETE =127, \n"
" AV_KEY_F1=256, \n"
" AV_KEY_F2, AV_KEY_F3, AV_KEY_F4, AV_KEY_F5, AV_KEY_F6, AV_KEY_F7, AV_KEY_F8, AV_KEY_F9, AV_KEY_F10, AV_KEY_F11, AV_KEY_F12, \n"
" AV_KEY_INSERT, \n"
" AV_KEY_LEFT, AV_KEY_UP, AV_KEY_RIGHT, AV_KEY_DOWN, \n"
" AV_KEY_PAGE_DOWN, AV_KEY_PAGE_UP, \n"
" AV_KEY_END, AV_KEY_HOME \n"
"}; \n"
"typedef struct av_Window { \n"
" int width, height; \n"
" int is_fullscreen; \n"
" int button; \n"
" int shift, alt, ctrl; \n"
" double fps; \n"
" void (*oncreate)(struct av_Window * self); \n"
" void (*onresize)(struct av_Window * self, int w, int h); \n"
" void (*onvisible)(struct av_Window * self, int state); \n"
" void (*ondraw)(struct av_Window * self); \n"
" void (*onkey)(struct av_Window * self, int event, int key); \n"
" void (*onmouse)(struct av_Window * self, int event, int button, int x, int y); \n"
"} av_Window; \n"
"av_Window * av_window_create(); \n"
"void av_window_setfullscreen(av_Window * self, int b); \n"
"void av_window_settitle(av_Window * self, const char * name); \n"
"void av_window_setdim(av_Window * self, int x, int y); \n"
"]] \n"
"local ffi = require 'ffi' \n"
"ffi.cdef(header) \n"
"return header \n";